Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 1024
      Handler: software.amazon.awscdk.examples.lambda.Search.LastGoodVersion
      CodeUri: /Users/samyalihamad/Library/Mobile Documents/com~apple~CloudDocs/Documents/Documents - Samy’s iMac/Projects/cloud-ds-explorer/lambda
      Runtime: java11
      Architectures:
        - x86_64