Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 1152
      Handler: cloud.ds.explorer.lambda.MedianTracker.ValuePostHandler
      CodeUri: /Users/samyalihamad/Documents/cloud-ds-explorer/lambda
      Runtime: java11
      Architectures:
        - x86_64