Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: cloud.ds.explorer.lambda.MedianTracker.ValueGetHandler
      CodeUri: /Users/samyalihamad/Documents/cloud-ds-explorer/lambda
      Runtime: java11
      Architectures:
        - x86_64